name: (EXAMPLE) Prod - Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-build-and-deploy:
    uses: ./.github/workflows/example-template-deploy.yml
    with:
      environment: 'dev'

    secrets: inherit
